apiVersion: v1
kind: Service
metadata:
  name: reviewapp-service
spec:
  type: NodePort
  selector:
    app: reviewapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
